spring.application.name: http-playground

logging:
  level:
    dev.jihogrammer.playground: DEBUG

---

spring.config.activate.on-profile: production
logging:
  level:
    dev.jihogrammer.playground: INFO
